# -*- coding: utf-8 -*-
"""okok2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9GMOgpnxDGdWKYPLlcE3keGCRCoz4P7
"""

import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
x = np.linspace(0, 10, 100)
y = np.sin(x)
z = np.cos(x)

plt.plot(x, y, label='sin(x)', color='blue')
plt.plot(x, z, label='cos(x)', color='red')
plt.title('Графики функций sin(x) и cos(x)')
plt.xlabel('x')
plt.ylabel('Значение функции')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
data = np.random.normal(0, 1, 1000)
plt.hist(data, bins=20, color='green', alpha=0.7)
plt.title('Гистограмма нормального распределения')
plt.xlabel('Значение')
plt.ylabel('Частота')
plt.grid(True)
plt.show()

matrix = np.random.randint(1, 11, size=(5, 5))
print("Матрица 5x5:")
print(matrix)
print("\nСреднее значение:", np.mean(matrix))
print("Максимальный элемент:", np.max(matrix))
print("Минимальный элемент:", np.min(matrix))
print("Сумма по столбцам:", np.sum(matrix, axis=0))

plt.figure(figsize=(8, 6))
plt.imshow(matrix, cmap='viridis')
plt.colorbar()
plt.title('Тепловая карта матрицы')

# Добавление аннотаций
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        plt.text(j, i, matrix[i, j], ha='center', va='center', color='white')
plt.show()

plt.figure(figsize=(12, 8))

# Первый подграфик: линейный график
plt.subplot(2, 2, 1)
x = np.linspace(0, 10, 50)
y = x**2
plt.plot(x, y, color='purple')
plt.title('y = x^2')
plt.grid(True)

# Второй подграфик: точечный график
plt.subplot(2, 2, 2)
x = np.random.rand(50)
y = np.random.rand(50)
plt.scatter(x, y, color='orange')
plt.title('Случайные точки')
plt.grid(True)

# Третий подграфик: столбчатая диаграмма
plt.subplot(2, 1, 2)
categories = ['A', 'B', 'C']
values = [3, 7, 2]
plt.bar(categories, values, color=['red', 'green', 'blue'])
plt.title('Столбчатая диаграмма')
plt.grid(True)

plt.tight_layout()
plt.show()
#https://colab.research.google.com/drive/1d9GMOgpnxDGdWKYPLlcE3keGCRCoz4P7?usp=sharing
